title = "Default CGA config"

[algorithm]
	method = "cga"

[cga]
	generations = 100000
	population = 500
	selection = 2
	output-probabilities = "./output-probabilities-duel"
	save-steps = 100

[rules]
	# Input rule is optional
	#input = "./optional"
	output = "./output-rules"

[db]
	db-dir = "/home/jgcarvalho/sync/data/multissdb/"
	db-name = "chameleonic.db"
	bucket-name = "proteins"
	init = "Seq"
	target = "All3"

[ca]
	initial-states = ["#","A","C","D","E","F","G","H","I","K","L","M","N","P","Q","R","S","T","V","W","Y"]
	transition-states = ["-","*","|","?"]
	has-joker = true
	r = 3
	steps = 100
	consensus = 11
