title = "Default Design config"

[algorithm]
	method = "design"

[design]
	# generations = 10
	population = 10000
	# selection = 400
	# tournament = 4
	output-probabilities = "./output-probabilities-eda"
	# save-steps = 1000

[rules]
	# Input rule is optional
	# input = "./optional"
	output = "./output-rules"

[proteindb]
	db-ip = "localhost"
	db-name = "proteindb_dev"
	collection-name = "protein"
	init = "seq_pdb"
	target = "ss3_cons_all"

[ca]
	initial-states = ["#","A","C","D","E","F","G","H","I","K","L","M","N","P","Q","R","S","T","V","W","Y"]
	transition-states = ["-","*","|","?"]
	has-joker = true
	r = 3
	steps = 100
	consensus = 5
